export let productsData = [
  {
    id: 1,
    title: 'Apple',
    description: 'Fresh red apples.',
    code: 'APL123',
    price: 0.5,
    status: true,
    stock: 150,
    category: 'Fruits',
    thumbnails: [],
  },
  {
    id: 2,
    title: 'Banana',
    description: 'Ripe yellow bananas.',
    code: 'BAN456',
    price: 0.3,
    status: true,
    stock: 200,
    category: 'Fruits',
    thumbnails: [],
  },
  {
    id: 3,
    title: 'Broccoli',
    description: 'Fresh green broccoli.',
    code: 'BRO789',
    price: 1.2,
    status: true,
    stock: 100,
    category: 'Vegetables',
    thumbnails: [],
  },
  {
    id: 4,
    title: 'Carrot',
    description: 'Crunchy orange carrots.',
    code: 'CAR012',
    price: 0.4,
    status: true,
    stock: 250,
    category: 'Vegetables',
    thumbnails: [],
  },
  {
    id: 5,
    title: 'Chicken Breast',
    description: 'Lean chicken breast.',
    code: 'CHICK345',
    price: 5.0,
    status: true,
    stock: 75,
    category: 'Meat',
    thumbnails: [],
  },
  {
    id: 6,
    title: 'Milk',
    description: '1 liter of fresh milk.',
    code: 'MIL678',
    price: 1.1,
    status: true,
    stock: 300,
    category: 'Dairy',
    thumbnails: [],
  },
  {
    id: 7,
    title: 'Bread',
    description: 'Whole grain bread.',
    code: 'BRD901',
    price: 2.0,
    status: true,
    stock: 180,
    category: 'Bakery',
    thumbnails: [],
  },
  {
    id: 8,
    title: 'Eggs',
    description: 'Dozen of organic eggs.',
    code: 'EGG234',
    price: 3.0,
    status: true,
    stock: 210,
    category: 'Dairy',
    thumbnails: [],
  },
  {
    id: 9,
    title: 'Orange Juice',
    description: '1 liter of fresh orange juice.',
    code: 'OJ567',
    price: 2.5,
    status: true,
    stock: 120,
    category: 'Beverages',
    thumbnails: [],
  },
  {
    id: 10,
    title: 'Cheese',
    description: 'Cheddar cheese block.',
    code: 'CHS890',
    price: 4.5,
    status: true,
    stock: 95,
    category: 'Dairy',
    thumbnails: [],
  },
]
